name: Release Please PreRelease Test

on:
  push:
    branches:
      - main
      - prerelease

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Release-Please for Branch
        run: |
          if [[ "${{ github.ref_name }}" == "prerelease" ]]; then
            echo "Configuring for pre-releases..."
            cp prerelease-config.json release-please-config.json
          fi

      - name: Run Release-Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}

      - name: Cleanup
        if: always()
        run: |
          if [[ "${{ github.ref_name }}" == "prerelease" ]]; then
            git checkout -- release-please-config.json || true
          fi